In [22]:
import numpy as np

In [23]:
data = np.random.randn(2,3)

In [24]:
data

array([[-0.29854302,  1.14368714,  0.81987559],
       [ 1.56930261,  0.15364882, -0.33836704]])

In [25]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

In [26]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
np.empty((2,3,2))

array([[[0.23232542, 0.3829509 ],
        [0.07766082, 0.1235165 ],
        [0.10600283, 0.00469613]],

       [[0.44812559, 0.05878572],
        [0.019075  , 0.09228366],
        [0.43016802, 0.06328194]]])

In [31]:
np.random.random()

0.1741987656942824

In [32]:
data.shape

(2, 3)

In [33]:
data.dtype

dtype('float64')

In [34]:
arr=np.random.random((4,3))

In [35]:
arr

array([[0.60477214, 0.2957021 , 0.41072048],
       [0.13824486, 0.11732814, 0.31695191],
       [0.72262348, 0.44443895, 0.14349407],
       [0.07804819, 0.85170075, 0.03318045]])

In [36]:
arr.mean(0)

array([0.38592217, 0.42729249, 0.22608673])

In [37]:
demand = arr - arr.mean(axis=0)
demand

array([[ 0.21884997, -0.13159039,  0.18463375],
       [-0.24767731, -0.30996434,  0.09086518],
       [ 0.33670131,  0.01714646, -0.08259266],
       [-0.30787397,  0.42440827, -0.19290628]])

In [38]:
demand.mean(0)

array([0., 0., 0.])

In [39]:
arr=np.empty((8,4))

In [40]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [42]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [43]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [44]:
arr = np.arange(15).reshape(3,5)

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

[1, 2, 3]

In [70]:
aa(a)

In [71]:
a

[1, 2, 3, 4]